### PR TITLE
do no drain backlog on backpressure

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Bug Fix

## PR Checklist
Check your PR fulfills the following:

- [x] Format code with the latest stable rustfmt

## Overview

Do not drain backlog when server enter backpressure.

### CODE REVIEW

**Comment by bobrik** [comment]
This helps, but it doesn't solve #216 completely.

**Comment by fakeshadow** [comment]
Well the backpressure happens when holding a connection so either we force push it to worker or drop it.

It also worth to notice that in your issue your go code actually is a slow request attack. Since that code opens a socket and does nothing. So it throttle your worker to the default slow request timeout. In real world you would want to deal with this attack with extra logic.

**Comment by bobrik** [comment]
> Well the backpressure happens when holding a connection so either we force push it to worker or drop it.

Why accept a connection above configured limit in the first place?

> The attacker would be able to reject legit connections that are not actual slow requests since your worker thread are busy with their slow attack requests.

The problem is that attacker can open more connections than configured limit because limit is not fully enforced. The problem you're describing can happen either way.

**Comment by fakeshadow** [comment]
> Why accept a connection above configured limit in the first place?

Because worker availability is atomicly checked and you don't want to iterator every worker's atomic state before accept a connection. For example if you have 32 workers you would need 32 atomic read of the worker state to decide if at certain point you can accept a connection or not. 

> The problem is that attacker can open more connections than configured limit because limit is not fully enforced. The problem you're describing can happen either way.

That's why I said you want extra logic to limit the remote peer from slow attack. You don't just drop connection like a blind man and say fuck it I don't care where it come from. 
The point here is you are using a slow request attack as an example of how legit accepting logic should work. I'm just pointing out they are different thing.

**Comment by fakeshadow** [comment]
That said I'm having an idea of reduce the atomic cost but it would probably be another PR.

**Review by robjtede — APPROVED** [review]

**Comment by fakeshadow** [comment]
There is issue with this change.
As backlogs are not drained on backpressure. Whoever bring the server back from backpressure should trigger accpet metond on every socket. Otherwise the backlog could be stucked until another new request comes in.

**Pull request merged**
