### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by JohnTitor**
Run CI on Windows and macOS.
It's experimental so I don't remove AppVeyor for now.
CC: #70 
See the check suite: https://github.com/JohnTitor/actix-net/actions

### CODE REVIEW

**Comment by fafhrd91** [comment]
Does it support codecov integration?

**Comment by JohnTitor** [comment]
I'm not sure, but I guess we can do it. In that case, we can also migrate from Travis.

**Comment by fafhrd91** [comment]
as I understand we still going to use linux travis ci?

**Comment by JohnTitor** [comment]
We can also run CI on Linux with GitHub Actions, so if we integrate codecov with Actions, I think Travis is unnecessary unless it has other parts to avoid using multiple CIs. (This PR doesn't contain Linux support and codecov integration though.)

**Pull request merged**
