### PR TITLE
router: don't decode %25 to '%'

### PR DESCRIPTION
**Pull request by aliemjay**
## PR Type

Bug fix

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Although the [documentation](https://actix.rs/docs/url-dispatch/) says that `path will be URL-unquoted and decoded into valid unicode string before matching pattern` , this is not the case - the matched url path segment may still have some percent encoded characters (specifically, `+` and `/`) .

Withh that given, `%25` should not unquoted to `%` to guarantee that matched segment is always a valid percent-encoded string so that the user can decode it himself. Consider the case in the linked issue!

Closes actix/actix-web#1157

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks reasonable to me 👍

**Comment by robjtede** [comment]
Havent thought about the implications yet but this would definitely need tests (and changelog).

**Comment by aliemjay** [comment]
The only implications I can think of are: url parameters the user gets from the `Path` extractor will now have `%` encoded as `%25`. Custom regex users (i.e. `{xxx:.*}`) are also affected 

This is a breaking change but, I think, is necessary for correctness.

**Comment by JohnTitor** [comment]
Since this changes the behavior anyway, it's definitely worth mentioning it on the changelog, even for correctness. I'm not sure about tests though, if you have some thoughts to harden it, it'd be great.

**Comment by aliemjay** [comment]
Added more tests and changelog.

Should this be mentioned in the migration guide?

**Comment by aliemjay** [comment]
Giving it more thought...

The question is does this really fixes the issue? Do we really want the user deal with percent-encoding in url parameters? I think thist should be totally abstracted away from the user!

**Comment by JohnTitor** [comment]
> The question is does this really fixes the issue? Do we really want the user deal with percent-encoding in url parameters? I think thist should be totally abstracted away from the user!

It definitely needs a decision (actix/actix-web#2248). I think resolving mixed behavior is a straightforward way for now.

> Should this be mentioned in the migration guide?

I think it's okay not to mention.

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
