### PR TITLE
`ResourceDef` redefine behavior rigorously

### LINKED ISSUE #376: dynamic prefixes should not be able match without a slash seperator
> Good! Now we have to find a solution for dynamic prefixes. One idea is to implement it in regex, where each dynamic prefix pattern is put inside a capture group with a pattern to detect segment boundary: `(original_regex_pattern)[/$]`. But this may add complexity. I'm not sure.

_Originally posted by @aliemjay in https://github.com/actix/actix-net/pull/373#discussion_r672394311_

test case that should not work but does:
```rust
let resource = ResourceDef::prefix(r"/id/{id:\d{3}}");
assert!(resource.is_match("/id/1234"));
assert_eq!(resource.find_match("/id/1234"), Some(7));
```

### PR DESCRIPTION
**Pull request by aliemjay**
## PR Type

INSERT_PR_TYPE

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Please see the docs.

* panic if pattern doesn't start with slash
* prefix with a trailing slash now requires an empty segment
* ~fixed a bug where an empty prefix matches only empty path~
* Closes #376 

This shouldn't affect the behavior in actix-web because we always insert slash.

Tests were taken from #378 .

### CODE REVIEW

**Comment by robjtede** [comment]
> panic if pattern doesn't start with slash

this breaks external_resources in actix web

**Comment by robjtede** [comment]
There's parts of this that I like but i'm going to go with #378 to solve #376 for now. It'll be a beta release so we've got time to revisit these points later.

**Comment by aliemjay** [comment]
> > panic if pattern doesn't start with slash
> 
> this breaks external_resources in actix web

Then just restrict this definition to matching while still allowing such constructing such pattern?

I still believe this is a more correct, yet simpler behavior to reason about.  If we are to keep the old behavior we can have the magic in actix-web.

**Comment by robjtede** [comment]
what i want to do actually, is clear up the router PRs here that are easy, release a beta, then move this crate to -web so we can catch breaks in web easier

**Comment by robjtede** [comment]
> I still believe this is a more correct

I believe you. We'll get back to it :)

**Comment by aliemjay** [comment]
superseded by actix/actix-web#2355

**Pull request closed without merging**
