### PR TITLE
rework actix-threadpool

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Refactor

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

`actix-threadpool` would spawn a fixed number of threads in a static pool and stay for the life of whole actix-app lifetime. I feel this is an overkill for majority use case and may bring up confusion.

This PR reworks the pool to use a dynamic strategy with the following behavior:
- Rename the worker thread name from "actix-web" to "actix-threadpool-worker".
- Start with 1 idle thread and when more jobs goes in it spawn more threads until hitting the upper limit.
- Any pool thread kept idle for 5 minutes would de spawn it self.

This PR is still not complete and need some help on tests and benchmarks.

### CODE REVIEW

**Comment by cdbattags** [comment]
@fafhrd91 I'd love your context on design decisions here. This kind of flys in the face of performance and what you had attempted at the beginning for speed.

@fakeshadow any chance we could change default behavior but still have old behavior as an option?

**Comment by fakeshadow** [comment]
From my limit tests I barely noticed any performance regress.

There are more configures to work with. e.g: 
```rust
let num = (num_cpus::get() * 5).to_string();
std::env::set_var("ACTIX_THREADPOOL", num.as_str());
std::env::set_var("ACTIX_THREADPOOL_MIN",  num.as_str());
std::env::set_var("ACTIX_THREADPOOL_TIMEOUT", "0");
```
This would have an identical behavior as the current pool.

**Comment by fakeshadow** [comment]
I added a benchmark [here](https://github.com/fakeshadow/jian_rs/tree/master/benches) to mimic the default behavior of actix-threadpool with the new one.
On my machine the result are at the same level.

**Comment by robjtede** [comment]
I think that apprehensions about replacing such an important part of the system could be quelled by releasing this as a separate crate that, once battle tested, could replace the original implementation. What do you think about making this a new `actix-dynamic-threadpool` package or something?

**Comment by fakeshadow** [comment]
I like the idea of a separate package or just leave this poll request as draft for now.
The dynamic pool can be easily import from my fork of actix-net in `Cargo.toml`. And I hope people can use it and give some feed back.

**Comment by robjtede** [comment]
I think my ideal plan would be to release this as a separate crate, with a dependency on a published version of your underlying jian_rs, and maybe add a feature flag to actix-web (post-v3) to replace the web::block call at developers choice. This would give more visibility and use to it that having to use a -net fork.

**Comment by fakeshadow** [comment]
Sounds a good plan. I can rename the project to `acitx-dynamic-threadpool` and remove `jian_rs` all together. If that's acceptable.

**Comment by robjtede** [comment]
> remove jian_rs all together

If I understand, that's the lib driving this new implementation, in which case I personally wouldn't have an issue using it as a dependency (as long as it's published). It's your work and you deserve to be credited for it. What did you have in mind by "removing" it?

**Comment by fakeshadow** [comment]
`jian_rs` have no essential dependency besides std. So it would be perfectly fine to copy paste the code to actix-threadpool and merge it into one separate package.

**Comment by robjtede** [comment]
Sure, inlining the package would be okay too.

**Comment by fakeshadow** [comment]
Ok. would do that and I believe this PR can be closed.

**Pull request closed without merging**
