### PR TITLE
WIP: Upgrade to Tokio 0.2.x

### PR DESCRIPTION
**Pull request by martell**
This PR hopes to update actix-net to using tokio 0.2.x stable.

Tracking list:

- [x] Update actix-codec **-- done** required updating the bytes dep also but that makes sense.
- [x] Update actix-server-config **-- done**

- [ ] actix-rt -- **In progress**
- [x] actix-codec **-- blocked on actix-rt** 
- [ ] actix-connect **-- blocked on https://github.com/bluejekyll/trust-dns/pull/932 and actix-rt** 
- [x] actix-ioframe **-- blocked on actix-rt** 
- [x] actix-server **-- blocked on actix-rt** 

External blockers:

- [x] https://github.com/alexcrichton/tokio-openssl/pull/13
- [x] https://github.com/quininer/tokio-rustls/pull/56

- [ ] https://github.com/bluejekyll/trust-dns/pull/932
    - [x] https://github.com/hyperium/h2/pull/428

Development Status: 

Currently thinking about actix-rt and this specific change in tokio
```
current_thread runtime is removed, use tokio::runtime::Runtime with
basic_scheduler instead.
```

### CODE REVIEW

**Comment by fafhrd91** [comment]
what is this?

**Comment by shirshak55** [comment]
@martell tokio-tls v2 has been merged?

**Comment by martell** [comment]
@shirshak55 it now seems to live here and is at version 0.2 also.
https://github.com/tokio-rs/tokio/tree/master/tokio-tls.

> what is this?
@fafhrd91 it is a draft PR to update to the release of tokio 0.2 which came out yesterday.
they collapsed a lot of crates into the main crate under feature flags so this is mostly dealing with that.
https://tokio.rs/blog/2019-11-tokio-0-2/

I'm excited to see how much of a performance boost the new scheduler will give actix-net and thus actix-web
See the blog post from Carl Lerche here.
https://tokio.rs/blog/2019-10-scheduler/

quininer/tokio-rustls#56 was merged so now that tokio-rustls has been updated too I'll get back to updating this after my work day.

**Comment by fafhrd91** [comment]
New scheduler won’t give any performance boost because actix does not use it and is not compatible.

Please make code compile at least before opening pr

**Comment by martell** [comment]
> Please make code compile at least before opening pr

For sure, this is why it is a draft :) I presume I will hit a few walls but I've made some progress today.

So far I have `actix-codec` and `actix-server-config` updated both compiling and running tests.

> New scheduler won’t give any performance boost because actix does not use it and is not compatible.

I believe this is actually the next blocker.
```
current_thread runtime is removed, use tokio::runtime::Runtime with
basic_scheduler instead.
```
It also notes
```
Standalone timer and net drivers are removed, use Runtime instead
```

I imagine that the runtime has to be switched to this `basic_scheduler` because of these changes.
Something like this ?
```
let mut runtime = runtime::Builder::new()
                .basic_scheduler()
                .enable_io()
                .build()
                .unwrap();
```

@fafhrd91 do you have any suggestions / input on this ?
I started playing around with `actix-rt` but I don't want to be yanking out things like `actix-rt/src/runtime.rs` without first discussing and having some clear direction on how the final modules should be structured before I proceed.

**Comment by martell** [comment]
I got a little too excited about having this working so I spent a few more hours testing various approaches to updating the scheduler.
It seems that I should have keep `actix-rt/src/builder.rs` so that the api can remain much the same.
I'll make a second attempt doing it this way at some point, but I am still open to recieving input / direction from people.
I also completed the migration of utils, ioframe testing and server to the new tokio changes by nulling our actix-rt to compile.

**Comment by cdbattags** [comment]
@fafhrd91 any more thoughts on how we want to deal with `actix-rt`?

**Comment by fafhrd91** [comment]
i am not entirely sure what is your purpose. you didnt ask about plans before opening pr.

**Comment by cdbattags** [comment]
> i am not entirely sure what is your purpose. you didnt ask about plans before opening pr.

What I want to know is what are the plans for `actix-rt` as it relates to https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.2?

**Comment by fafhrd91** [comment]
master is on tokio-0.2

**Pull request closed without merging**
