### PR TITLE
`spawn` should allow futures with non-unit outputs

### PR DESCRIPTION
**Pull request by ibraheemdev**
## PR Type
Feature

## PR Checklist
- [x] Tests for the changes have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

### CODE REVIEW

**Comment by robjtede** [comment]
This is non-breaking, right?

**Comment by ibraheemdev** [comment]
It's considered a minor breaking change.

**Comment by robjtede** [comment]
Can you show me an example of a case where this would break code?

**Comment by ibraheemdev** [comment]
I don't have an example, but I think it could potentially affect type inference. 

> The type of an argument to a function, or its return value, can be generalized to use generics, including by introducing a new type parameter (as long as it can be instantiated to the original type). ... Introducing generics in this way can potentially create type inference failures, but these are considered acceptable per the principles of the RFC: they only require local annotations that could have been inserted in advance.

https://rust-lang.github.io/rfcs/1105-api-evolution.html#minor-change-generalizing-to-generics-1

**Comment by robjtede** [comment]
I suspect we're safe from inference failures because we're not actually introducing a new generic, we're just using the associated type of an existing generic.

**Comment by ibraheemdev** [comment]
Yeah, that's probably true, but there could always be some quirky edge case that we didn't account for. `actix_rt::spawn` is used rarely for anything more than `spawn(foo)` or `let handle = spawn(foo); ... handle.await`, so I either way the risk of breakage is very small.

**Pull request merged**
