### PR TITLE
Start the std::future and tokio 0.2 migration

### PR DESCRIPTION
**Pull request by semtexzv**
This PR contains the work to start the migration of actix ecosystem to std::future, and tokio 0.2.

Currently, the actix-rt, actix-codec and actix-threadpool libraries are done. Big part of this migration will be actix-service, and thus, I invite you to help.

@fafhrd91 I'd like you to create a separate branch, so this work can live in this repository instead of my fork.

### CODE REVIEW

**Comment by fafhrd91** [comment]
@semtexzv I just sent you invitation to the actix org, you should be able to create branches.

**Comment by cdbattags** [comment]
@fafhrd91 how might I go about getting access to the org as well? Or at least access to the new std-future branch at least? I'd like to help manage all the current PRs and assist @semtexzv with the conversion in time for the tokio 2.0 release.

**Comment by cdbattags** [comment]
Awesome, now that I have access I'll coordinate getting all these PRs/changes into the main std-future branch. Should be able to start either tonight or tomorrow morning. I'll be sure to update the current branch to master beforehand as well.

**Comment by fafhrd91** [comment]
@cdbattags not so fast. I need to play with std future first. also after using services in real system I have some insights, I want to change api.

**Comment by cdbattags** [comment]
Ok, not a problem. What's currently in std-future is just a cut of what was started here. Feel free to put a PR against it as the "in development" branch for anything futures 0.3.

I just wanted to have a solid place to start instead of having many different PRs.

**Comment by cdbattags** [comment]
Shall I go ahead and close this PR now that we're working off `std-future` branch and PR #57?

**Comment by fafhrd91** [comment]
leave it for now

**Comment by cdbattags** [comment]
Ok, but ideally let's have the single branch/PR asap so I can track against all your insights and potential api changes? Doesn't necessarily have to compile. We can tweak Travis to allow errors on the single branch.

The more visibility the better so others might assist.

**Comment by fafhrd91** [comment]
we have to port actix-service first, everything else does not matter at the moment.

**Comment by cdbattags** [comment]
> we have to port actix-service first, everything else does not matter at the moment.

Do you have any current work that's not tracked you'd like to toss upstream somewhere? Otherwise, let's start from #49, no?

**Comment by cdbattags** [comment]
Looks like there's already plenty on `semtexzv:std-future-service` but maybe let's get that work living on this repo and get Travis wired properly so we're not going off of a fork?

**Comment by cdbattags** [comment]
Closing this so we're not confused where we currently stand.

**Pull request closed without merging**
